// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZAGS.Model;

namespace ZAGS.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210607173105_Test1")]
    partial class Test1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("ZAGS.Model.Marriage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fio1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fio2")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Registration")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Marriage");
                });
#pragma warning restore 612, 618
        }
    }
}
